name: "SRGAN_model"
platform: "tensorflow_savedmodel"
input [
  {
    name: "keras_tensor"
    data_type: TYPE_FP32
    dims: [640, 640, 3]
  }
]
output [
  {
    name: "output_0"
    data_type: TYPE_FP32
    dims: [640, 640, 3]
  }
]

max_batch_size: 8

dynamic_batching{
    preferred_batch_size: [2, 8]
    max_queue_delay_microseconds: 10
}

instance_group[
    {
        count: 2
        kind: KIND_GPU
        gpus: [0, 1]
    }
]

version_policy: {
  specific: { versions: [1] }
}